server:
  port: 7071
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8
    username: root
    password: 12345678
#####设置日志######
logging:
   file: ..//logs//gateway.log
   level:
     root: info